import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google"; // Import supported fonts from Google
import "./globals.css";
import DashboardWrapper from "./dashboardWrapper";

// Import Roboto and Roboto Mono with weight property
const roboto = Roboto({
  variable: "--font-roboto", // Custom CSS variable for Roboto font
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Define the font weights you want to use
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono", // Custom CSS variable for Roboto Mono font
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Define the font weights you want to use
});

export const metadata: Metadata = {
  title: "Collabova",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${robotoMono.variable} antialiased`} // Apply both fonts
      >
        <DashboardWrapper>{children}</DashboardWrapper>
      </body>
    </html>
  );
}
